# Generated by Django 4.1.7 on 2023-03-11 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CzatOgolny",
            fields=[
                (
                    "ID_wiadomosci",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("tresc_wiadomosci", models.CharField(max_length=255, null=True)),
                ("data_wiadomosci", models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CzatPrywatny",
            fields=[
                (
                    "ID_wiadomosci",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("tresc_wiadomosci", models.CharField(max_length=255, null=True)),
                ("data_wiadomosci", models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Grupy",
            fields=[
                ("ID", models.IntegerField(primary_key=True, serialize=False)),
                ("Nazwa", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="Studenci",
            fields=[
                ("ID_studenta", models.IntegerField(primary_key=True, serialize=False)),
                ("imie", models.CharField(max_length=50)),
                ("nazwisko", models.CharField(max_length=50)),
                ("mail", models.CharField(max_length=50)),
                (
                    "ID_grupy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.grupy"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="student", name="group",),
        migrations.RemoveField(model_name="student", name="requests",),
        migrations.DeleteModel(name="Group",),
        migrations.DeleteModel(name="Supervisor",),
        migrations.AddField(
            model_name="czatprywatny",
            name="ID_studenta_nadawcy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nadawca",
                to="app.studenci",
            ),
        ),
        migrations.AddField(
            model_name="czatprywatny",
            name="ID_studenta_odbiorcy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="odbiorca",
                to="app.studenci",
            ),
        ),
        migrations.AddField(
            model_name="czatogolny",
            name="ID_studenta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.studenci"
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipient_requests",
                to="app.studenci",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sender_requests",
                to="app.studenci",
            ),
        ),
        migrations.DeleteModel(name="Student",),
    ]
