# Generated by Django 4.1.7 on 2023-03-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_czatogolny_czatprywatny_grupy_studenci_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="czatprywatny",
            name="ID_wiadomosci",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
