# Generated by Django 4.1.7 on 2023-03-12 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_czatprywatny_id_wiadomosci"),
    ]

    operations = [
        migrations.AlterField(
            model_name="czatogolny",
            name="ID_wiadomosci",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
