# Generated by Django 4.1.7 on 2023-03-14 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_czatogolny_id_wiadomosci"),
    ]

    operations = []
