# Generated by Django 4.1.7 on 2023-03-14 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_auto_20230315_0010"),
    ]

    operations = []
