# Generated by Django 4.1.7 on 2023-03-17 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_auto_20230315_0020"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grupy",
            name="ID",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="studenci",
            name="ID_grupy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="id_grupy",
                to="app.grupy",
            ),
        ),
        migrations.AlterField(
            model_name="studenci",
            name="ID_studenta",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="studenci",
            name="mail",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name="Transfer",
            fields=[
                ("ID_transfer", models.AutoField(primary_key=True, serialize=False)),
                ("approved", models.BooleanField(default=False)),
                (
                    "exchanger_student_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchanged_transfers",
                        to="app.studenci",
                    ),
                ),
                (
                    "requester_student_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requested_transfers",
                        to="app.studenci",
                    ),
                ),
            ],
        ),
    ]
