# Generated by Django 4.1.7 on 2023-03-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_grupy_id_alter_studenci_id_grupy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transfer",
            name="approved",
            field=models.BooleanField(default=None),
        ),
    ]
